### ISSUE TITLE
样式能否不污染全局

### ISSUE THREAD

**Issue by lyz810** [react-component/select#776]
```less
* {box-sizing: border-box;}
```
这选择器影响范围太大，容易对页面其他组件进行污染，应收到select-prefix内部

https://github.com/react-component/select/blob/de5d98d463019f5c00b22e05de925078a54eb946/assets/index.less#L3
